### ISSUE TITLE
Export should also take care of inlines

### ISSUE THREAD

**Issue by bevenky** [praekelt/django-export#4] opened 2011-09-13 13:44 UTC
While exporting models related inlines should also be exported

I have it working for json as an admin action. you may want to include this in export.

https://gist.github.com/1213838

**Comment by qoda** [comment] 2018-05-11 08:51
Although I think this is useful the issue is now not related to the current version. Closing. Contributions should also be in the form of Pull Requests.

**Closed by qoda** 2018-05-11 08:51 UTC
